/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RatesRouteImport } from './routes/rates'
import { Route as OgImageRouteImport } from './routes/og-image'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GalleryIndexRouteImport } from './routes/gallery.index'
import { Route as GalleryCategoryRouteImport } from './routes/gallery/$category'
import { Route as DeliverSlugRouteImport } from './routes/deliver/$slug'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe/webhook'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RatesRoute = RatesRouteImport.update({
  id: '/rates',
  path: '/rates',
  getParentRoute: () => rootRouteImport,
} as any)
const OgImageRoute = OgImageRouteImport.update({
  id: '/og-image',
  path: '/og-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryIndexRoute = GalleryIndexRouteImport.update({
  id: '/gallery/',
  path: '/gallery/',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryCategoryRoute = GalleryCategoryRouteImport.update({
  id: '/gallery/$category',
  path: '/gallery/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliverSlugRoute = DeliverSlugRouteImport.update({
  id: '/deliver/$slug',
  path: '/deliver/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/og-image': typeof OgImageRoute
  '/rates': typeof RatesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/deliver/$slug': typeof DeliverSlugRoute
  '/gallery/$category': typeof GalleryCategoryRoute
  '/gallery': typeof GalleryIndexRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/og-image': typeof OgImageRoute
  '/rates': typeof RatesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/deliver/$slug': typeof DeliverSlugRoute
  '/gallery/$category': typeof GalleryCategoryRoute
  '/gallery': typeof GalleryIndexRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/og-image': typeof OgImageRoute
  '/rates': typeof RatesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/deliver/$slug': typeof DeliverSlugRoute
  '/gallery/$category': typeof GalleryCategoryRoute
  '/gallery/': typeof GalleryIndexRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/og-image'
    | '/rates'
    | '/sitemap.xml'
    | '/deliver/$slug'
    | '/gallery/$category'
    | '/gallery'
    | '/api/stripe/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/og-image'
    | '/rates'
    | '/sitemap.xml'
    | '/deliver/$slug'
    | '/gallery/$category'
    | '/gallery'
    | '/api/stripe/webhook'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/og-image'
    | '/rates'
    | '/sitemap.xml'
    | '/deliver/$slug'
    | '/gallery/$category'
    | '/gallery/'
    | '/api/stripe/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  OgImageRoute: typeof OgImageRoute
  RatesRoute: typeof RatesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  DeliverSlugRoute: typeof DeliverSlugRoute
  GalleryCategoryRoute: typeof GalleryCategoryRoute
  GalleryIndexRoute: typeof GalleryIndexRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rates': {
      id: '/rates'
      path: '/rates'
      fullPath: '/rates'
      preLoaderRoute: typeof RatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og-image': {
      id: '/og-image'
      path: '/og-image'
      fullPath: '/og-image'
      preLoaderRoute: typeof OgImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery/': {
      id: '/gallery/'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery/$category': {
      id: '/gallery/$category'
      path: '/gallery/$category'
      fullPath: '/gallery/$category'
      preLoaderRoute: typeof GalleryCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deliver/$slug': {
      id: '/deliver/$slug'
      path: '/deliver/$slug'
      fullPath: '/deliver/$slug'
      preLoaderRoute: typeof DeliverSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  OgImageRoute: OgImageRoute,
  RatesRoute: RatesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  DeliverSlugRoute: DeliverSlugRoute,
  GalleryCategoryRoute: GalleryCategoryRoute,
  GalleryIndexRoute: GalleryIndexRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
